bloodRelations/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('relations.urls')),
]

relations/urls.py
from django.urls import path
from . import views

app_name = 'relations'

urlpatterns = [
    path('', views.people_list, name='home'),
    path('new', views.add_person, name='add_person'),
    path('<int:pk>', views.people_detail, name='detail'),
    path('<int:pk>/receives', views.people_receives, name='receives'),
    path('<int:pk>/gives', views.people_gives, name='gives'),
]

relations/models.py
from django.db import models


class Person(models.Model):
    name = models.CharField(
        max_length=50,
    )
    gender = models.CharField(
        max_length=1,
    )
    dob = models.DateField()
    blood_type = models.CharField(
        max_length=3,
    )
    height = models.DecimalField(
        max_digits=5,
        decimal_places=2,
    )
    weight = models.DecimalField(
        max_digits=5,
        decimal_places=2,
    )

    objects = models.Manager()

    def __str__(self):
        return self.name

relations/forms.py
from django import forms
from .models import Person
from .utils import blood_types, gender

class PersonForm(forms.Form):
    name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': 'Name'}),
    )
    gender = forms.ChoiceField(choices=gender)
    dob = forms.DateField(widget=forms.TextInput(attrs={'placeholder': '2001-01-30'}),)
    blood_type = forms.ChoiceField(choices=blood_types)
    height = forms.DecimalField(
        max_digits=5,
        decimal_places=2,
        widget=forms.TextInput(attrs={'placeholder': 'Height in Cm'}),)
    weight = forms.DecimalField(
        max_digits=5,
        decimal_places=2,
        widget=forms.TextInput(attrs={'placeholder': 'Weight in Kg'}),
    )

relations/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from django.forms import ModelForm

from .models import Person
from .forms import PersonForm
from .utils import blood_relationships, get_age, get_bmi, paginate


def people_list(request):
    people = Person.objects.all().order_by('-id')
    people = paginate(request, people, 10)
    context = {
        'people': people,
    }
    return render(request,
        'relations/people_list.html',
        context=context
    )

def people_detail(request, pk):
    try:
        person = Person.objects.get(pk=pk)
    except:
        raise Http404("Person does not exist")
    age = get_age(person.dob)
    context = {
        'person': person,
        'age' : age,
        'bmi': get_bmi(person.height, person.weight),
    }
    return render(request,
        'relations/people_detail.html',
        context=context
    )

def people_receives(request, pk):
    try:
        person = Person.objects.get(pk=pk)
    except:
        raise Http404("Person does not exist")
    people = Person.objects.filter(blood_type__in=blood_relationships[person.blood_type]["receives"]).exclude(pk=person.id)
    context = {
        'person': person,
        'people': people,
    }
    return render(request,
        'relations/people_receives.html',
        context=context
    )

def people_gives(request, pk):
    try:
        person = Person.objects.get(pk=pk)
    except:
        raise Http404("Person does not exist")
    people = Person.objects.filter(blood_type__in=blood_relationships[person.blood_type]["gives"]).exclude(pk=person.id)
    context = {
        'person': person,
        'people': people,
    }
    return render(request,
        'relations/people_gives.html',
        context=context
    )


def add_person(request): 
    form = PersonForm(request.POST or None) 
    if form.is_valid():
        cd = form.cleaned_data
        person = Person(**cd)
        person.save()
        return HttpResponseRedirect('/')
    context = {
        'form': form,
    }
    return render(request,
        "relations/add_person.html",
        context
    ) 

relations/templates/relations/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Blood Relations {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}?{% now "U" %}">
<body>
    {% include "relations/_nav.html" %}
    <main>
        {% block content %}{% endblock content %}
    </main>
</body>
</html>

relations/templates/relations/_nav.html
<header>
    <nav>
        <div class="nav-left">
            <ul>
                <li><a href="{% url 'relations:home' %}" id="brand-name">Blood Bank</a></li>
            </ul>
        </div>
        <div class="nav-right">
            <ul>
                <li><a href=" {% url 'relations:add_person' %} ">Add New Person</a></li>
            </ul>
        </div>
    </nav>
</header>
<br><br><br>

relations/templates/relations/_paginator.html
{% if model_object.has_other_pages %}
<ul class="pagination">
    {% if model_object.has_previous %}
    <a href="?page={{ model_object.previous_page_number }}">&laquo;</a>
    {% else %}
    <a class="disabled">&laquo;</a>
    {% endif %}
    {% for i in model_object.paginator.page_range %}
    {% if model_object.number == i %}
    <a href="#" class="active">{{i}}</a>
    {% else %}
        <a href="?page={{ i }}">{{ i }}</a>
    {% endif %}
    {% endfor %}
    {% if model_object.has_next %}
    <a href="?page={{ model_object.next_page_number }}">&raquo;</a>
    {% else %}
    <a class="disabled">&raquo;</a>
    {% endif %}
</ul>
{% endif %}

relations/templates/relations/_person.html
<div>
    <p>Name: <a href=" {% url 'relations:detail' person.pk %} ">{{person.name}}</a></p>
    <p>Gender: {% if person.gender == "M" %}Male{% else %}Female{% endif %}</p>
    <p>Blood Group: {{person.blood_type}}</p>
</div>

relations/templates/relations/add_person.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %} 
    {{ form.as_p }} 
    <input type="submit" value="Submit"> 
</form> 

relations/templates/relations/people_detail.html
{% extends 'relations/_base.html' %}

{% block content %}
<div>
    <p><strong>Name:</strong> {{person.name}}</p>
    <p><strong>Gender:</strong> {% if person.gender == "M" %}Male{% else %}Female{% endif %}</p>
    <p><strong>Age:</strong> {{age}}</p>
    <p><strong>Blood Group:</strong> {{person.blood_type}}</p>
    <p><strong>Height:</strong> {{person.height}}</p>
    <p><strong>Weight:</strong> {{person.weight}}</p>
    <p><strong>BMI:</strong> {{bmi}}</p>
</div>
{% endblock content %}

relations/templates/relations/people_gives.html
{% extends 'relations/_base.html' %}
{% load extras %}

{% block content %}
    <div>
        <h2>{{person.name|capitalize}} with {{person.blood_type}} can donate to</h2>
    </div>
    <hr>
    {% for each in people%}
        <div>
            <p>Name: <a href=" {% url 'relations:detail' each.pk %} ">{{each.name}}</a></p>
            <p>Gender: {% if each.gender == "M" %}Male{% else %}Female{% endif %}</p>
            <p>Blood Group: {{each.blood_type}}</p>
        </div>
        <hr>
    {% endfor %}
{% endblock content %}

relations/templates/relations/people_list.html
{% extends 'relations/_base.html' %}

{% block common %}
<div>
    <div>
        <a href=" {% url 'relations:add_person' %} ">Add New Person</a>
    </div>
</div>
{% endblock common %}

{% block content %}
{% for person in people %}
    <div>
    <p>{{person.name}} ({{person.blood_type}})</p>
    <p><a href="{% url 'relations:detail' pk=person.id %}">Show More Info</a></p>
    <p><a href="{% url 'relations:receives' pk=person.id %}">Receives Blood from</a></p>
    <p><a href="{% url 'relations:gives' pk=person.id %}">Donates Blood to</a></p>
    </div>
    <hr>
{% endfor %}
{% include "relations/_paginator.html" with model_object=people %}
{% endblock content %}

relations/templates/relations/people_receives.html
{% extends 'relations/_base.html' %}
{% load extras %}

{% block content %}
    <div>
        <h2>{{person.name|capitalize}} with {{person.blood_type}} can receive from</h2>
    </div>
    <hr>
    {% for each in people%}
    {% include "relations/_person.html" with person=each %}
    <hr>
    {% endfor %}
{% endblock content %}